databases:
  - name: makpower_db
    databaseName: makpower
    user: admin

services:
  - type: web
    name: purchase-request-manager
    env: node
    buildCommand: npm run build
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: makpower_db
          property: connectionString
