export const initialUsers = [
  {
    id: "u-admin",
    name: "Super Admin",
    email: "admin@makpowerindia.com",
    password: "MakPower#Admin2026!",
    role: "superadmin",
    designation: "System Admin",
    status: "active"
  },
  {
    id: "u-owner",
    name: "Company Owner",
    email: "owner@makpowerindia.com",
    password: "MakPower#Owner2026!",
    role: "owner",
    designation: "Owner",
    status: "active"
  },
  {
    id: "u-anees",
    name: "Anees",
    email: "anees@makpowerindia.com",
    password: "MakPower#Anees2026!",
    role: "purchaser",
    designation: "Purchaser",
    status: "active"
  },
  {
    id: "u-nitin",
    name: "Nitin Kumar",
    email: "nitin@makpowerindia.com",
    password: "MakPower#Nitin2026!",
    role: "purchaser",
    designation: "Packing",
    status: "active"
  },
  {
    id: "u-rahul",
    name: "Rahul",
    email: "rahul@makpowerindia.com",
    password: "MakPower#Rahul2026!",
    role: "purchaser",
    designation: "Accounts and Updates",
    status: "active"
  },
  {
    id: "u-coordinator",
    name: "Logistics PC",
    email: "pc@makpowerindia.com",
    password: "MakPower#Coord2026!",
    role: "coordinator",
    designation: "Logistics",
    status: "active"
  },
  // CRM Executive Team
  {
    id: "u-ankita",
    name: "Ankita",
    email: "ankita@makpowerindia.com",
    password: "MakPower#CRM2026!",
    role: "crm",
    designation: "CRM Executive",
    phone: "+91 98101 23401",
    territory: "North & West Region",
    status: "active"
  },
  {
    id: "u-ajit",
    name: "Ajit",
    email: "ajit@makpowerindia.com",
    password: "MakPower#CRM2026!",
    role: "crm",
    designation: "CRM Executive",
    phone: "+91 98101 23402",
    territory: "Central & East Region",
    status: "active"
  },
  {
    id: "u-prince",
    name: "Prince",
    email: "prince@makpowerindia.com",
    password: "MakPower#CRM2026!",
    role: "crm",
    designation: "CRM Executive",
    phone: "+91 98101 23403",
    territory: "South Region & Key Accounts",
    status: "active"
  },
  {
    id: "u-simran",
    name: "Simran",
    email: "simran@makpowerindia.com",
    password: "MakPower#CRM2026!",
    role: "crm",
    designation: "CRM Executive",
    phone: "+91 98101 23404",
    territory: "NCR & Delhi Region",
    status: "active"
  },
  {
    id: "u-harish",
    name: "Harish",
    email: "harish@makpowerindia.com",
    password: "MakPower#CRM2026!",
    role: "crm",
    designation: "CRM Executive",
    phone: "+91 98101 23405",
    territory: "UP & Bihar Region",
    status: "active"
  },
  // Sample ASMs (Area Sales Managers)
  {
    id: "u-asm-vikram",
    name: "Vikram Sharma",
    email: "vikram.asm@makpowerindia.com",
    password: "MakPower#ASM2026!",
    role: "asm",
    designation: "Area Sales Manager (ASM)",
    parentCrmId: "u-ankita",
    phone: "+91 98765 11001",
    territory: "Rajasthan & Punjab Area",
    status: "active"
  },
  {
    id: "u-asm-rohit",
    name: "Rohit Verma",
    email: "rohit.asm@makpowerindia.com",
    password: "MakPower#ASM2026!",
    role: "asm",
    designation: "Area Sales Manager (ASM)",
    parentCrmId: "u-ajit",
    phone: "+91 98765 11002",
    territory: "Kolkata & Odisha Area",
    status: "active"
  },
  // Sample TSMs (Territory Sales Managers)
  {
    id: "u-tsm-manoj",
    name: "Manoj Kumar",
    email: "manoj.tsm@makpowerindia.com",
    password: "MakPower#TSM2026!",
    role: "tsm",
    designation: "Territory Sales Manager (TSM)",
    parentCrmId: "u-ankita",
    phone: "+91 98765 22001",
    territory: "Jaipur City & Alwar",
    status: "active"
  },
  {
    id: "u-tsm-suresh",
    name: "Suresh Gupta",
    email: "suresh.tsm@makpowerindia.com",
    password: "MakPower#TSM2026!",
    role: "tsm",
    designation: "Territory Sales Manager (TSM)",
    parentCrmId: "u-simran",
    phone: "+91 98765 22002",
    territory: "East Delhi & Noida",
    status: "active"
  }
];

export const initialDesignations = [
  { id: "d-owner", title: "Owner", role: "owner", description: "Company Executive / Owner Dashboard Access" },
  { id: "d-crm", title: "CRM Executive", role: "crm", description: "Customer Relationship & Party Sales Management" },
  { id: "d-asm", title: "Area Sales Manager (ASM)", role: "asm", description: "Area Sales Team & Regional Party Network" },
  { id: "d-tsm", title: "Territory Sales Manager (TSM)", role: "tsm", description: "Territory Sales & Direct Dealer Relations" },
  { id: "d-accounts-updates", title: "Accounts and Updates", role: "purchaser", description: "Accounts & Financial Order Updates" },
  { id: "d-purchaser", title: "Purchaser", role: "purchaser", description: "Purchase Requisitions & Vendor Management" },
  { id: "d-packing", title: "Packing", role: "purchaser", description: "Packing & Production Purchasing" },
  { id: "d-accounts", title: "Accounts", role: "purchaser", description: "Payment & Accounts Reconciliation" },
  { id: "d-warehouse", title: "Warehouse", role: "purchaser", description: "Inventory & Stock Receiving" },
  { id: "d-logistics", title: "Logistics", role: "coordinator", description: "Cargo & Shipment Dispatch Management" },
  { id: "d-admin", title: "System Admin", role: "superadmin", description: "Full System Administration" }
];

export const initialVendors = [];
export const initialRequests = [];
export const initialCargoShipments = [];
export const initialCargoCompanies = [];
export const initialItems = [];

// Initial CRM Parties (Pre-mapped to Ankita, Ajit, Prince, Simran, Harish)
export const initialCrmParties = [
  {
    id: "pty-101",
    name: "Shree Ganesh Electronics & Traders",
    contactPerson: "Ganesh Sharma",
    phone: "+91 98290 12345",
    email: "shreeganesh.jpr@gmail.com",
    city: "Jaipur",
    state: "Rajasthan",
    gstin: "08AABCS1429B1Z2",
    creditLimit: 500000,
    outstanding: 145000,
    paymentTerms: "30 Days",
    assignedCrmId: "u-ankita",
    assignedCrmName: "Ankita",
    assignedAsmId: "u-asm-vikram",
    assignedAsmName: "Vikram Sharma",
    assignedTsmId: "u-tsm-manoj",
    assignedTsmName: "Manoj Kumar",
    status: "Active",
    createdAt: "2026-01-15"
  },
  {
    id: "pty-102",
    name: "Apex Power Solutions",
    contactPerson: "Rajesh Khandelwal",
    phone: "+91 94140 88765",
    email: "apexpower.raj@yahoo.com",
    city: "Jodhpur",
    state: "Rajasthan",
    gstin: "08AAECP8831A1Z9",
    creditLimit: 750000,
    outstanding: 210000,
    paymentTerms: "21 Days",
    assignedCrmId: "u-ankita",
    assignedCrmName: "Ankita",
    assignedAsmId: "u-asm-vikram",
    assignedAsmName: "Vikram Sharma",
    assignedTsmId: "",
    assignedTsmName: "",
    status: "Active",
    createdAt: "2026-02-10"
  },
  {
    id: "pty-103",
    name: "Eastern Mobile & Battery Hub",
    contactPerson: "Subhash Banerjee",
    phone: "+91 98301 44556",
    email: "eastern.kol@gmail.com",
    city: "Kolkata",
    state: "West Bengal",
    gstin: "19AABCE9921C1ZV",
    creditLimit: 1000000,
    outstanding: 380000,
    paymentTerms: "45 Days",
    assignedCrmId: "u-ajit",
    assignedCrmName: "Ajit",
    assignedAsmId: "u-asm-rohit",
    assignedAsmName: "Rohit Verma",
    assignedTsmId: "",
    assignedTsmName: "",
    status: "Active",
    createdAt: "2026-01-20"
  },
  {
    id: "pty-104",
    name: "Pioneer Telecom Distributors",
    contactPerson: "Amitabh Sen",
    phone: "+91 97482 33211",
    email: "pioneer.patna@gmail.com",
    city: "Patna",
    state: "Bihar",
    gstin: "10AACCP4412K1Z4",
    creditLimit: 600000,
    outstanding: 95000,
    paymentTerms: "30 Days",
    assignedCrmId: "u-ajit",
    assignedCrmName: "Ajit",
    assignedAsmId: "",
    assignedAsmName: "",
    assignedTsmId: "",
    assignedTsmName: "",
    status: "Active",
    createdAt: "2026-03-01"
  },
  {
    id: "pty-105",
    name: "Southern Power Accessories",
    contactPerson: "K. R. Venkatesh",
    phone: "+91 98450 77889",
    email: "venkatesh.blr@southernpower.in",
    city: "Bengaluru",
    state: "Karnataka",
    gstin: "29AABCS8891M1ZU",
    creditLimit: 1200000,
    outstanding: 420000,
    paymentTerms: "30 Days",
    assignedCrmId: "u-prince",
    assignedCrmName: "Prince",
    assignedAsmId: "",
    assignedAsmName: "",
    assignedTsmId: "",
    assignedTsmName: "",
    status: "Active",
    createdAt: "2026-01-18"
  },
  {
    id: "pty-106",
    name: "Royal Digital & Mobile Care",
    contactPerson: "Sunil Reddy",
    phone: "+91 99890 55432",
    email: "royalreddy.hyd@gmail.com",
    city: "Hyderabad",
    state: "Telangana",
    gstin: "36AACCR2231F1ZS",
    creditLimit: 800000,
    outstanding: 175000,
    paymentTerms: "15 Days",
    assignedCrmId: "u-prince",
    assignedCrmName: "Prince",
    assignedAsmId: "",
    assignedAsmName: "",
    assignedTsmId: "",
    assignedTsmName: "",
    status: "Active",
    createdAt: "2026-02-14"
  },
  {
    id: "pty-107",
    name: "Delhi Mega Tech Wholesale",
    contactPerson: "Kavita Mehra",
    phone: "+91 98110 99887",
    email: "megatech.delhi@gmail.com",
    city: "New Delhi",
    state: "Delhi",
    gstin: "07AAACD9941G1Z1",
    creditLimit: 1500000,
    outstanding: 650000,
    paymentTerms: "30 Days",
    assignedCrmId: "u-simran",
    assignedCrmName: "Simran",
    assignedAsmId: "",
    assignedAsmName: "",
    assignedTsmId: "u-tsm-suresh",
    assignedTsmName: "Suresh Gupta",
    status: "Active",
    createdAt: "2026-01-05"
  },
  {
    id: "pty-108",
    name: "Noida Mobile Gallery",
    contactPerson: "Deepak Choudhary",
    phone: "+91 98711 44332",
    email: "deepak.noida@yahoo.com",
    city: "Noida",
    state: "Uttar Pradesh",
    gstin: "09AABCD3312H1ZQ",
    creditLimit: 400000,
    outstanding: 80000,
    paymentTerms: "15 Days",
    assignedCrmId: "u-simran",
    assignedCrmName: "Simran",
    assignedAsmId: "",
    assignedAsmName: "",
    assignedTsmId: "u-tsm-suresh",
    assignedTsmName: "Suresh Gupta",
    status: "Active",
    createdAt: "2026-02-22"
  },
  {
    id: "pty-109",
    name: "Awadh Electricals & Battery House",
    contactPerson: "Mahesh Chandra",
    phone: "+91 94150 66778",
    email: "awadh.lko@gmail.com",
    city: "Lucknow",
    state: "Uttar Pradesh",
    gstin: "09AAACE5521J1ZX",
    creditLimit: 700000,
    outstanding: 190000,
    paymentTerms: "30 Days",
    assignedCrmId: "u-harish",
    assignedCrmName: "Harish",
    assignedAsmId: "",
    assignedAsmName: "",
    assignedTsmId: "",
    assignedTsmName: "",
    status: "Active",
    createdAt: "2026-01-12"
  },
  {
    id: "pty-110",
    name: "Varanasi Power Hub",
    contactPerson: "Girish Tripathi",
    phone: "+91 94500 22119",
    email: "varanasi.power@gmail.com",
    city: "Varanasi",
    state: "Uttar Pradesh",
    gstin: "09AACCV1192M1ZK",
    creditLimit: 500000,
    outstanding: 120000,
    paymentTerms: "21 Days",
    assignedCrmId: "u-harish",
    assignedCrmName: "Harish",
    assignedAsmId: "",
    assignedAsmName: "",
    assignedTsmId: "",
    assignedTsmName: "",
    status: "Active",
    createdAt: "2026-03-05"
  }
];

// Initial Sales Orders for item-wise sales reporting (empty by default)
export const initialCrmSalesOrders = [];

// Initial Dispatched records for dispatch reporting (empty by default)
export const initialCrmDispatches = [];

// Initial IMS Transactions (empty by default)
export const initialImsTransactions = [];
