export const initialUsers = [
  {
    id: "u-admin",
    name: "Super Admin",
    email: "admin@makpowerindia.com",
    password: "MakPower#Admin2026!",
    role: "superadmin",
    designation: "System Admin",
    status: "active"
  },
  {
    id: "u-owner",
    name: "Company Owner",
    email: "owner@makpowerindia.com",
    password: "MakPower#Owner2026!",
    role: "owner",
    designation: "Owner",
    status: "active"
  },
  {
    id: "u-anees",
    name: "Anees",
    email: "anees@makpowerindia.com",
    password: "MakPower#Anees2026!",
    role: "purchaser",
    designation: "Purchaser",
    status: "active"
  },
  {
    id: "u-nitin",
    name: "Nitin Kumar",
    email: "nitin@makpowerindia.com",
    password: "MakPower#Nitin2026!",
    role: "purchaser",
    designation: "Packing",
    status: "active"
  },
  {
    id: "u-rahul",
    name: "Rahul",
    email: "rahul@makpowerindia.com",
    password: "MakPower#Rahul2026!",
    role: "purchaser",
    designation: "Accounts and Updates",
    status: "active"
  },
  {
    id: "u-coordinator",
    name: "Logistics PC",
    email: "pc@makpowerindia.com",
    password: "MakPower#Coord2026!",
    role: "coordinator",
    designation: "Logistics",
    status: "active"
  },
  // CRM Executive Team
  {
    id: "u-ankita",
    name: "Ankita",
    email: "ankita@makpowerindia.com",
    password: "MakPower#CRM2026!",
    role: "crm",
    designation: "CRM Executive",
    phone: "+91 98101 23401",
    territory: "North & West Region",
    status: "active"
  },
  {
    id: "u-ajit",
    name: "Ajit",
    email: "ajit@makpowerindia.com",
    password: "MakPower#CRM2026!",
    role: "crm",
    designation: "CRM Executive",
    phone: "+91 98101 23402",
    territory: "Central & East Region",
    status: "active"
  },
  {
    id: "u-prince",
    name: "Prince",
    email: "prince@makpowerindia.com",
    password: "MakPower#CRM2026!",
    role: "crm",
    designation: "CRM Executive",
    phone: "+91 98101 23403",
    territory: "South Region & Key Accounts",
    status: "active"
  },
  {
    id: "u-simran",
    name: "Simran",
    email: "simran@makpowerindia.com",
    password: "MakPower#CRM2026!",
    role: "crm",
    designation: "CRM Executive",
    phone: "+91 98101 23404",
    territory: "NCR & Delhi Region",
    status: "active"
  },
  {
    id: "u-harish",
    name: "Harish",
    email: "harish@makpowerindia.com",
    password: "MakPower#CRM2026!",
    role: "crm",
    designation: "CRM Executive",
    phone: "+91 98101 23405",
    territory: "UP & Bihar Region",
    status: "active"
  },
  // Sample ASMs (Area Sales Managers)
  {
    id: "u-asm-vikram",
    name: "Vikram Sharma",
    email: "vikram.asm@makpowerindia.com",
    password: "MakPower#ASM2026!",
    role: "asm",
    designation: "Area Sales Manager (ASM)",
    parentCrmId: "u-ankita",
    phone: "+91 98765 11001",
    territory: "Rajasthan & Punjab Area",
    status: "active"
  },
  {
    id: "u-asm-rohit",
    name: "Rohit Verma",
    email: "rohit.asm@makpowerindia.com",
    password: "MakPower#ASM2026!",
    role: "asm",
    designation: "Area Sales Manager (ASM)",
    parentCrmId: "u-ajit",
    phone: "+91 98765 11002",
    territory: "Kolkata & Odisha Area",
    status: "active"
  },
  // Sample TSMs (Territory Sales Managers)
  {
    id: "u-tsm-manoj",
    name: "Manoj Kumar",
    email: "manoj.tsm@makpowerindia.com",
    password: "MakPower#TSM2026!",
    role: "tsm",
    designation: "Territory Sales Manager (TSM)",
    parentCrmId: "u-ankita",
    phone: "+91 98765 22001",
    territory: "Jaipur City & Alwar",
    status: "active"
  },
  {
    id: "u-tsm-suresh",
    name: "Suresh Gupta",
    email: "suresh.tsm@makpowerindia.com",
    password: "MakPower#TSM2026!",
    role: "tsm",
    designation: "Territory Sales Manager (TSM)",
    parentCrmId: "u-simran",
    phone: "+91 98765 22002",
    territory: "East Delhi & Noida",
    status: "active"
  }
];

export const initialDesignations = [
  { id: "d-owner", title: "Owner", role: "owner", description: "Company Executive / Owner Dashboard Access" },
  { id: "d-crm", title: "CRM Executive", role: "crm", description: "Customer Relationship & Party Sales Management" },
  { id: "d-asm", title: "Area Sales Manager (ASM)", role: "asm", description: "Area Sales Team & Regional Party Network" },
  { id: "d-tsm", title: "Territory Sales Manager (TSM)", role: "tsm", description: "Territory Sales & Direct Dealer Relations" },
  { id: "d-accounts-updates", title: "Accounts and Updates", role: "purchaser", description: "Accounts & Financial Order Updates" },
  { id: "d-purchaser", title: "Purchaser", role: "purchaser", description: "Purchase Requisitions & Vendor Management" },
  { id: "d-packing", title: "Packing", role: "purchaser", description: "Packing & Production Purchasing" },
  { id: "d-accounts", title: "Accounts", role: "purchaser", description: "Payment & Accounts Reconciliation" },
  { id: "d-warehouse", title: "Warehouse", role: "purchaser", description: "Inventory & Stock Receiving" },
  { id: "d-logistics", title: "Logistics", role: "coordinator", description: "Cargo & Shipment Dispatch Management" },
  { id: "d-admin", title: "System Admin", role: "superadmin", description: "Full System Administration" }
];

export const initialVendors = [];
export const initialRequests = [];
export const initialCargoShipments = [];
export const initialCargoCompanies = [];
export const initialItems = [];

// Initial CRM Parties (Pre-mapped to Ankita, Ajit, Prince, Simran, Harish)
export const initialCrmParties = [
  {
    id: "pty-101",
    name: "Shree Ganesh Electronics & Traders",
    contactPerson: "Ganesh Sharma",
    phone: "+91 98290 12345",
    email: "shreeganesh.jpr@gmail.com",
    city: "Jaipur",
    state: "Rajasthan",
    gstin: "08AABCS1429B1Z2",
    creditLimit: 500000,
    outstanding: 145000,
    paymentTerms: "30 Days",
    assignedCrmId: "u-ankita",
    assignedCrmName: "Ankita",
    assignedAsmId: "u-asm-vikram",
    assignedAsmName: "Vikram Sharma",
    assignedTsmId: "u-tsm-manoj",
    assignedTsmName: "Manoj Kumar",
    status: "Active",
    createdAt: "2026-01-15"
  },
  {
    id: "pty-102",
    name: "Apex Power Solutions",
    contactPerson: "Rajesh Khandelwal",
    phone: "+91 94140 88765",
    email: "apexpower.raj@yahoo.com",
    city: "Jodhpur",
    state: "Rajasthan",
    gstin: "08AAECP8831A1Z9",
    creditLimit: 750000,
    outstanding: 210000,
    paymentTerms: "21 Days",
    assignedCrmId: "u-ankita",
    assignedCrmName: "Ankita",
    assignedAsmId: "u-asm-vikram",
    assignedAsmName: "Vikram Sharma",
    assignedTsmId: "",
    assignedTsmName: "",
    status: "Active",
    createdAt: "2026-02-10"
  },
  {
    id: "pty-103",
    name: "Eastern Mobile & Battery Hub",
    contactPerson: "Subhash Banerjee",
    phone: "+91 98301 44556",
    email: "eastern.kol@gmail.com",
    city: "Kolkata",
    state: "West Bengal",
    gstin: "19AABCE9921C1ZV",
    creditLimit: 1000000,
    outstanding: 380000,
    paymentTerms: "45 Days",
    assignedCrmId: "u-ajit",
    assignedCrmName: "Ajit",
    assignedAsmId: "u-asm-rohit",
    assignedAsmName: "Rohit Verma",
    assignedTsmId: "",
    assignedTsmName: "",
    status: "Active",
    createdAt: "2026-01-20"
  },
  {
    id: "pty-104",
    name: "Pioneer Telecom Distributors",
    contactPerson: "Amitabh Sen",
    phone: "+91 97482 33211",
    email: "pioneer.patna@gmail.com",
    city: "Patna",
    state: "Bihar",
    gstin: "10AACCP4412K1Z4",
    creditLimit: 600000,
    outstanding: 95000,
    paymentTerms: "30 Days",
    assignedCrmId: "u-ajit",
    assignedCrmName: "Ajit",
    assignedAsmId: "",
    assignedAsmName: "",
    assignedTsmId: "",
    assignedTsmName: "",
    status: "Active",
    createdAt: "2026-03-01"
  },
  {
    id: "pty-105",
    name: "Southern Power Accessories",
    contactPerson: "K. R. Venkatesh",
    phone: "+91 98450 77889",
    email: "venkatesh.blr@southernpower.in",
    city: "Bengaluru",
    state: "Karnataka",
    gstin: "29AABCS8891M1ZU",
    creditLimit: 1200000,
    outstanding: 420000,
    paymentTerms: "30 Days",
    assignedCrmId: "u-prince",
    assignedCrmName: "Prince",
    assignedAsmId: "",
    assignedAsmName: "",
    assignedTsmId: "",
    assignedTsmName: "",
    status: "Active",
    createdAt: "2026-01-18"
  },
  {
    id: "pty-106",
    name: "Royal Digital & Mobile Care",
    contactPerson: "Sunil Reddy",
    phone: "+91 99890 55432",
    email: "royalreddy.hyd@gmail.com",
    city: "Hyderabad",
    state: "Telangana",
    gstin: "36AACCR2231F1ZS",
    creditLimit: 800000,
    outstanding: 175000,
    paymentTerms: "15 Days",
    assignedCrmId: "u-prince",
    assignedCrmName: "Prince",
    assignedAsmId: "",
    assignedAsmName: "",
    assignedTsmId: "",
    assignedTsmName: "",
    status: "Active",
    createdAt: "2026-02-14"
  },
  {
    id: "pty-107",
    name: "Delhi Mega Tech Wholesale",
    contactPerson: "Kavita Mehra",
    phone: "+91 98110 99887",
    email: "megatech.delhi@gmail.com",
    city: "New Delhi",
    state: "Delhi",
    gstin: "07AAACD9941G1Z1",
    creditLimit: 1500000,
    outstanding: 650000,
    paymentTerms: "30 Days",
    assignedCrmId: "u-simran",
    assignedCrmName: "Simran",
    assignedAsmId: "",
    assignedAsmName: "",
    assignedTsmId: "u-tsm-suresh",
    assignedTsmName: "Suresh Gupta",
    status: "Active",
    createdAt: "2026-01-05"
  },
  {
    id: "pty-108",
    name: "Noida Mobile Gallery",
    contactPerson: "Deepak Choudhary",
    phone: "+91 98711 44332",
    email: "deepak.noida@yahoo.com",
    city: "Noida",
    state: "Uttar Pradesh",
    gstin: "09AABCD3312H1ZQ",
    creditLimit: 400000,
    outstanding: 80000,
    paymentTerms: "15 Days",
    assignedCrmId: "u-simran",
    assignedCrmName: "Simran",
    assignedAsmId: "",
    assignedAsmName: "",
    assignedTsmId: "u-tsm-suresh",
    assignedTsmName: "Suresh Gupta",
    status: "Active",
    createdAt: "2026-02-22"
  },
  {
    id: "pty-109",
    name: "Awadh Electricals & Battery House",
    contactPerson: "Mahesh Chandra",
    phone: "+91 94150 66778",
    email: "awadh.lko@gmail.com",
    city: "Lucknow",
    state: "Uttar Pradesh",
    gstin: "09AAACE5521J1ZX",
    creditLimit: 700000,
    outstanding: 190000,
    paymentTerms: "30 Days",
    assignedCrmId: "u-harish",
    assignedCrmName: "Harish",
    assignedAsmId: "",
    assignedAsmName: "",
    assignedTsmId: "",
    assignedTsmName: "",
    status: "Active",
    createdAt: "2026-01-12"
  },
  {
    id: "pty-110",
    name: "Varanasi Power Hub",
    contactPerson: "Girish Tripathi",
    phone: "+91 94500 22119",
    email: "varanasi.power@gmail.com",
    city: "Varanasi",
    state: "Uttar Pradesh",
    gstin: "09AACCV1192M1ZK",
    creditLimit: 500000,
    outstanding: 120000,
    paymentTerms: "21 Days",
    assignedCrmId: "u-harish",
    assignedCrmName: "Harish",
    assignedAsmId: "",
    assignedAsmName: "",
    assignedTsmId: "",
    assignedTsmName: "",
    status: "Active",
    createdAt: "2026-03-05"
  }
];

// Initial Sales Orders for item-wise sales reporting
export const initialCrmSalesOrders = [
  {
    id: "so-1001",
    orderNo: "SO-2026-001",
    orderDate: "2026-06-01",
    partyId: "pty-101",
    partyName: "Shree Ganesh Electronics & Traders",
    itemModel: "MP-PB-10000 Power Bank",
    category: "Power Bank",
    orderQty: 500,
    unitPriceInr: 450,
    totalInr: 225000,
    dispatchedQty: 500,
    pendingQty: 0,
    status: "Dispatched",
    assignedCrmId: "u-ankita",
    assignedAsmId: "u-asm-vikram",
    assignedTsmId: "u-tsm-manoj",
    notes: "Regular monthly dealer stock order"
  },
  {
    id: "so-1002",
    orderNo: "SO-2026-002",
    orderDate: "2026-06-03",
    partyId: "pty-101",
    partyName: "Shree Ganesh Electronics & Traders",
    itemModel: "MP-TC-65W Fast Charger",
    category: "Charger",
    orderQty: 300,
    unitPriceInr: 320,
    totalInr: 96000,
    dispatchedQty: 200,
    pendingQty: 100,
    status: "Partially Dispatched",
    assignedCrmId: "u-ankita",
    assignedAsmId: "u-asm-vikram",
    assignedTsmId: "u-tsm-manoj",
    notes: "Balance 100 pcs awaiting next production batch"
  },
  {
    id: "so-1003",
    orderNo: "SO-2026-003",
    orderDate: "2026-06-05",
    partyId: "pty-102",
    partyName: "Apex Power Solutions",
    itemModel: "MP-CB-TypeC Fast Cable",
    category: "Cables",
    orderQty: 1000,
    unitPriceInr: 65,
    totalInr: 65000,
    dispatchedQty: 1000,
    pendingQty: 0,
    status: "Dispatched",
    assignedCrmId: "u-ankita",
    assignedAsmId: "u-asm-vikram",
    assignedTsmId: "",
    notes: "Full carton shipment delivered"
  },
  {
    id: "so-1004",
    orderNo: "SO-2026-004",
    orderDate: "2026-06-06",
    partyId: "pty-103",
    partyName: "Eastern Mobile & Battery Hub",
    itemModel: "MP-PB-20000 Ultra Power Bank",
    category: "Power Bank",
    orderQty: 400,
    unitPriceInr: 820,
    totalInr: 328000,
    dispatchedQty: 400,
    pendingQty: 0,
    status: "Dispatched",
    assignedCrmId: "u-ajit",
    assignedAsmId: "u-asm-rohit",
    assignedTsmId: "",
    notes: "Dispatched via TCI Express"
  },
  {
    id: "so-1005",
    orderNo: "SO-2026-005",
    orderDate: "2026-06-08",
    partyId: "pty-104",
    partyName: "Pioneer Telecom Distributors",
    itemModel: "MP-TC-65W Fast Charger",
    category: "Charger",
    orderQty: 250,
    unitPriceInr: 320,
    totalInr: 80000,
    dispatchedQty: 0,
    pendingQty: 250,
    status: "Pending Dispatch",
    assignedCrmId: "u-ajit",
    assignedAsmId: "",
    assignedTsmId: "",
    notes: "Payment clearance received, packing in progress"
  },
  {
    id: "so-1006",
    orderNo: "SO-2026-006",
    orderDate: "2026-06-04",
    partyId: "pty-105",
    partyName: "Southern Power Accessories",
    itemModel: "MP-PB-10000 Power Bank",
    category: "Power Bank",
    orderQty: 800,
    unitPriceInr: 450,
    totalInr: 360000,
    dispatchedQty: 800,
    pendingQty: 0,
    status: "Dispatched",
    assignedCrmId: "u-prince",
    assignedAsmId: "",
    assignedTsmId: "",
    notes: "VRL Logistics door delivery"
  },
  {
    id: "so-1007",
    orderNo: "SO-2026-007",
    orderDate: "2026-06-09",
    partyId: "pty-106",
    partyName: "Royal Digital & Mobile Care",
    itemModel: "MP-BT-Earbuds Pro",
    category: "Audio",
    orderQty: 300,
    unitPriceInr: 580,
    totalInr: 174000,
    dispatchedQty: 150,
    pendingQty: 150,
    status: "Partially Dispatched",
    assignedCrmId: "u-prince",
    assignedAsmId: "",
    assignedTsmId: "",
    notes: "Partial 150 units sent via Blue Dart"
  },
  {
    id: "so-1008",
    orderNo: "SO-2026-008",
    orderDate: "2026-06-02",
    partyId: "pty-107",
    partyName: "Delhi Mega Tech Wholesale",
    itemModel: "MP-PB-10000 Power Bank",
    category: "Power Bank",
    orderQty: 1200,
    unitPriceInr: 440,
    totalInr: 528000,
    dispatchedQty: 1200,
    pendingQty: 0,
    status: "Dispatched",
    assignedCrmId: "u-simran",
    assignedAsmId: "",
    assignedTsmId: "u-tsm-suresh",
    notes: "Local tempo delivery from Delhi godown"
  },
  {
    id: "so-1009",
    orderNo: "SO-2026-009",
    orderDate: "2026-06-07",
    partyId: "pty-108",
    partyName: "Noida Mobile Gallery",
    itemModel: "MP-TC-20W Dual Adapter",
    category: "Charger",
    orderQty: 400,
    unitPriceInr: 190,
    totalInr: 76000,
    dispatchedQty: 0,
    pendingQty: 400,
    status: "Pending Dispatch",
    assignedCrmId: "u-simran",
    assignedAsmId: "",
    assignedTsmId: "u-tsm-suresh",
    notes: "Ready for dispatch scheduled tomorrow"
  },
  {
    id: "so-1010",
    orderNo: "SO-2026-010",
    orderDate: "2026-06-05",
    partyId: "pty-109",
    partyName: "Awadh Electricals & Battery House",
    itemModel: "MP-PB-20000 Ultra Power Bank",
    category: "Power Bank",
    orderQty: 350,
    unitPriceInr: 820,
    totalInr: 287000,
    dispatchedQty: 350,
    pendingQty: 0,
    status: "Dispatched",
    assignedCrmId: "u-harish",
    assignedAsmId: "",
    assignedTsmId: "",
    notes: "Safe Express LR #7788912"
  },
  {
    id: "so-1011",
    orderNo: "SO-2026-011",
    orderDate: "2026-06-10",
    partyId: "pty-110",
    partyName: "Varanasi Power Hub",
    itemModel: "MP-CB-TypeC Fast Cable",
    category: "Cables",
    orderQty: 600,
    unitPriceInr: 65,
    totalInr: 39000,
    dispatchedQty: 300,
    pendingQty: 300,
    status: "Partially Dispatched",
    assignedCrmId: "u-harish",
    assignedAsmId: "",
    assignedTsmId: "",
    notes: "First lot 300 units dispatched"
  }
];

// Initial Dispatched records for dispatch reporting
export const initialCrmDispatches = [
  {
    id: "dsp-501",
    orderId: "so-1001",
    orderNo: "SO-2026-001",
    partyId: "pty-101",
    partyName: "Shree Ganesh Electronics & Traders",
    itemModel: "MP-PB-10000 Power Bank",
    dispatchedQty: 500,
    transporterName: "Gati-KWE Logistics",
    docketNo: "GATI-8890212",
    invoiceNo: "INV-MP-26-0881",
    dispatchDate: "2026-06-02",
    deliveryDate: "2026-06-04",
    status: "Delivered",
    assignedCrmId: "u-ankita",
    assignedAsmId: "u-asm-vikram",
    assignedTsmId: "u-tsm-manoj"
  },
  {
    id: "dsp-502",
    orderId: "so-1002",
    orderNo: "SO-2026-002",
    partyId: "pty-101",
    partyName: "Shree Ganesh Electronics & Traders",
    itemModel: "MP-TC-65W Fast Charger",
    dispatchedQty: 200,
    transporterName: "V-Trans India Ltd",
    docketNo: "VT-554109",
    invoiceNo: "INV-MP-26-0894",
    dispatchDate: "2026-06-05",
    deliveryDate: "",
    status: "In Transit",
    assignedCrmId: "u-ankita",
    assignedAsmId: "u-asm-vikram",
    assignedTsmId: "u-tsm-manoj"
  },
  {
    id: "dsp-503",
    orderId: "so-1003",
    orderNo: "SO-2026-003",
    partyId: "pty-102",
    partyName: "Apex Power Solutions",
    itemModel: "MP-CB-TypeC Fast Cable",
    dispatchedQty: 1000,
    transporterName: "Jaipur Golden Transport",
    docketNo: "JGT-992110",
    invoiceNo: "INV-MP-26-0902",
    dispatchDate: "2026-06-07",
    deliveryDate: "2026-06-09",
    status: "Delivered",
    assignedCrmId: "u-ankita",
    assignedAsmId: "u-asm-vikram",
    assignedTsmId: ""
  },
  {
    id: "dsp-504",
    orderId: "so-1004",
    orderNo: "SO-2026-004",
    partyId: "pty-103",
    partyName: "Eastern Mobile & Battery Hub",
    itemModel: "MP-PB-20000 Ultra Power Bank",
    dispatchedQty: 400,
    transporterName: "TCI Express Ltd",
    docketNo: "TCI-771249",
    invoiceNo: "INV-MP-26-0915",
    dispatchDate: "2026-06-07",
    deliveryDate: "",
    status: "In Transit",
    assignedCrmId: "u-ajit",
    assignedAsmId: "u-asm-rohit",
    assignedTsmId: ""
  },
  {
    id: "dsp-505",
    orderId: "so-1006",
    orderNo: "SO-2026-006",
    partyId: "pty-105",
    partyName: "Southern Power Accessories",
    itemModel: "MP-PB-10000 Power Bank",
    dispatchedQty: 800,
    transporterName: "VRL Logistics Ltd",
    docketNo: "VRL-4410982",
    invoiceNo: "INV-MP-26-0888",
    dispatchDate: "2026-06-06",
    deliveryDate: "2026-06-09",
    status: "Delivered",
    assignedCrmId: "u-prince",
    assignedAsmId: "",
    assignedTsmId: ""
  },
  {
    id: "dsp-506",
    orderId: "so-1007",
    orderNo: "SO-2026-007",
    partyId: "pty-106",
    partyName: "Royal Digital & Mobile Care",
    itemModel: "MP-BT-Earbuds Pro",
    dispatchedQty: 150,
    transporterName: "Blue Dart Express",
    docketNo: "BD-88912304",
    invoiceNo: "INV-MP-26-0922",
    dispatchDate: "2026-06-10",
    deliveryDate: "",
    status: "In Transit",
    assignedCrmId: "u-prince",
    assignedAsmId: "",
    assignedTsmId: ""
  },
  {
    id: "dsp-507",
    orderId: "so-1008",
    orderNo: "SO-2026-008",
    partyId: "pty-107",
    partyName: "Delhi Mega Tech Wholesale",
    itemModel: "MP-PB-10000 Power Bank",
    dispatchedQty: 1200,
    transporterName: "Direct Factory Delivery",
    docketNo: "DL-LOCAL-099",
    invoiceNo: "INV-MP-26-0870",
    dispatchDate: "2026-06-03",
    deliveryDate: "2026-06-03",
    status: "Delivered",
    assignedCrmId: "u-simran",
    assignedAsmId: "",
    assignedTsmId: "u-tsm-suresh"
  },
  {
    id: "dsp-508",
    orderId: "so-1010",
    orderNo: "SO-2026-010",
    partyId: "pty-109",
    partyName: "Awadh Electricals & Battery House",
    itemModel: "MP-PB-20000 Ultra Power Bank",
    dispatchedQty: 350,
    transporterName: "Safexpress Pvt Ltd",
    docketNo: "SFX-9988124",
    invoiceNo: "INV-MP-26-0911",
    dispatchDate: "2026-06-06",
    deliveryDate: "2026-06-08",
    status: "Delivered",
    assignedCrmId: "u-harish",
    assignedAsmId: "",
    assignedTsmId: ""
  },
  {
    id: "dsp-509",
    orderId: "so-1011",
    orderNo: "SO-2026-011",
    partyId: "pty-110",
    partyName: "Varanasi Power Hub",
    itemModel: "MP-CB-TypeC Fast Cable",
    dispatchedQty: 300,
    transporterName: "Trackon Couriers",
    docketNo: "TRK-661209",
    invoiceNo: "INV-MP-26-0935",
    dispatchDate: "2026-06-11",
    deliveryDate: "",
    status: "In Transit",
    assignedCrmId: "u-harish",
    assignedAsmId: "",
    assignedTsmId: ""
  }
];
